// import { Inter } from "next/font/google";
// import "./globals.css";
// import App from "../compnents/App";
// import { NavBar } from "../compnents/NavBar";
// import Test from "@/compnents/Test";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <App>
//           {/* <NavBar /> */}
//           <Test />
//           {children}
//         </App>
//       </body>
//     </html>
//   );
// }

import { Inter } from "next/font/google";
import NavBar from "@/compnents/NavBar";
import App from "../compnents/App";
// Importing global style css:
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// Next RootLayout Template component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body className=" flex min-h-screen flex-col px-4 py-2">
        <header>
          <NavBar />
        </header>
        <main className="grow py-3">
          <App>{children}</App>
        </main>
        <footer className="border-t py-3 text-center text-xs text-slate-500">
          This is a footer
        </footer>
      </body>
    </html>
  );
}
